language: node_js
node_js:
- 16
cache:
  directories:
  - node_modules
  - $HOME/.cache/pip
before_install:
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
script:
- npm test
after_success:
- npm run predeploy
- npm run build
- |-
  # If this is a non-main branch build: Deploy the storyboard to S3
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" != "main" ]; then
    # Force installation from pip cache, to reduce the amount of ~/.local we need to store in the Travis cache
    pip install --user awscli | cat

    aws s3 cp --recursive storybook-static s3://collaborne-carrot-styles/${TRAVIS_BRANCH}/${TRAVIS_COMMIT}/

    curl \
      -X POST \
      -H "Accept: application/vnd.github.v3+json" \
      -H "Authorization: token ${GITHUB_TOKEN}" \
      https://api.github.com/repos/${TRAVIS_REPO_SLUG}/commits/${TRAVIS_COMMIT}/comments \
      -d "{\"body\":\"Storybook deployed at http://collaborne-carrot-styles.s3-website-eu-west-1.amazonaws.com/${TRAVIS_BRANCH}/${TRAVIS_COMMIT}/\"}"
    fi
before_deploy:
- |-
  # `before_deploy` runs before each deploy provider, so if there is already a build_package_version defined don't bother working
  # through this again.
  # Note that we only do this when this is a non-tagged build; for tagged builds the assumption is that the version inside
  # `package.json` is correct.
  if [ -z "${build_package_version}" ] && [ -z "${TRAVIS_TAG}" ]; then
    # Build a version that properly compares as prerelease on top of the existing version. If the existing version is
    # a pre-release already separate further components with '.', otherwise use '-'.
    # The safe branch name is used as dist tag and as part of the version as prerelease identifier, so must follow
    # the strict semver grammar rules.
    safe_branch_name=$(echo "${TRAVIS_BRANCH}" | tr -d '\n' | tr -cd 'A-Za-z0-9-')
    ts=$(date +%Y%m%d%H%M%S)
    package_version=$(node -p 'require("./package.json").version')
    if echo "${package_version}" | grep -- '-' >/dev/null 2>&1; then
      prerelease_separator=.
    else
      prerelease_separator=-
    fi

    build_package_version=${package_version}${prerelease_separator}${safe_branch_name}.${ts}
    echo "build_package_version calculated as ${build_package_version}" >&2
    npm --no-git-tag-version version ${build_package_version}
  fi
deploy:
- provider: npm
  email: npm@collaborne.com
  api_key:
    secure: "YZy5EPjg5QVDgqSFLCcBLqY0NnOKtqeLdN3+yBOAJzD0e8Ol5OXPwKuX2vVxGCiIYmVIT1qp1B997mUY2EXbZ2OByMO5aCfQex6aHoLFnPV2a0wwmertX6gQz/yZlVu3btOGBbs/zA+HZEVj/S+26kZDJrC/SSV8QLtWHE8tel9UqI+uvc4APDwl2gKn2uL2f51Po8b7cpNgX72q129PTZAK7ZlHTciZxkgWlv1Sd2kb4dSK6ILAHAnmyuCYMQBAMaA8zFXjeTxr+aM+qcBZ69VnjFe70KcdqpC5+OTXkyZbabutVjFIGGxjnol4VNLFc5AGqAr3esWqVT/cwGlXM3hQjh1mrtskXJe/ch5udIbo7ZxRSeHwUeT4H6Ylxm/7c//yvxwHIg5KEU8GFssMzKbcEbRjZ0F2zQoGD9ZrygnPQ/WvATL9kZMrQ2AdGfFKFv1Pe6X4o26ceMkffZVxngHIu7QYLeAfdC/ru5UISKEunEqbPdZZ1OAVq2A9xV7SPvjmWJK0KES1fQaEBo/s659967fGd5YeFC3DbPT44pb49PBeAH9Nj7zm2jyIDbqc0HaJ/m1SzKPEqzeiWksv3dzinJe4ZDufgTf7oOUJXY735Uo1YqXzaODaxGQ9hQZImvlTus7qNipp9V8jlxkmeHMO24Ke6JsxTK1drftu+V4="
  on:
    tags: true
    condition: $(node -e 'console.log("v" + require("./package.json").version)') = ${TRAVIS_TAG}
  skip_cleanup: true
- provider: npm
  email: npm@collaborne.com
  api_key:
    secure: "YZy5EPjg5QVDgqSFLCcBLqY0NnOKtqeLdN3+yBOAJzD0e8Ol5OXPwKuX2vVxGCiIYmVIT1qp1B997mUY2EXbZ2OByMO5aCfQex6aHoLFnPV2a0wwmertX6gQz/yZlVu3btOGBbs/zA+HZEVj/S+26kZDJrC/SSV8QLtWHE8tel9UqI+uvc4APDwl2gKn2uL2f51Po8b7cpNgX72q129PTZAK7ZlHTciZxkgWlv1Sd2kb4dSK6ILAHAnmyuCYMQBAMaA8zFXjeTxr+aM+qcBZ69VnjFe70KcdqpC5+OTXkyZbabutVjFIGGxjnol4VNLFc5AGqAr3esWqVT/cwGlXM3hQjh1mrtskXJe/ch5udIbo7ZxRSeHwUeT4H6Ylxm/7c//yvxwHIg5KEU8GFssMzKbcEbRjZ0F2zQoGD9ZrygnPQ/WvATL9kZMrQ2AdGfFKFv1Pe6X4o26ceMkffZVxngHIu7QYLeAfdC/ru5UISKEunEqbPdZZ1OAVq2A9xV7SPvjmWJK0KES1fQaEBo/s659967fGd5YeFC3DbPT44pb49PBeAH9Nj7zm2jyIDbqc0HaJ/m1SzKPEqzeiWksv3dzinJe4ZDufgTf7oOUJXY735Uo1YqXzaODaxGQ9hQZImvlTus7qNipp9V8jlxkmeHMO24Ke6JsxTK1drftu+V4="
  on:
    all_branches: true
    condition: ${TRAVIS_TAG} == ""
  skip_cleanup: true
  tag: ${safe_branch_name}
- provider: pages
  skip_cleanup: true
  local_dir: storybook-static
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
env:
  global:
  # NPM_TOKEN
  - secure: "Nt4HJ0n4fmbwT0JpdmNqCDNs6WTgVcXHjyFA5HF92wp7QjagmIOvKtK+DcyxLzgaJUd0VRC79kye0QJKUfDT2Yt4lf5o8ZpLwiOK96f81OMYVrp2Z9JRfjiC3QwexTtJjMIU1MUHHmPd+EZAzLj2///ZBI+xbjN1mK9CSCAQH8jRzbvbTcIx0q4JSbTEv2KuFZfgaoyQYUQnfLnfrA26Oom3j9TGDP6yJi47bUk71ibS1KCH0Da32mm/5DflWwcMdHwgqd2KAd8YYP0Dv3OwIj6pvNNP6v8uVsw2YXETsZn/DPKLUp795J2UC5jQihtP66HOl5K3kvENcsFUMMJcA6VipNfOsApsa1j++/GjEJo5dR2J+BW5/ozjJYznYvAULH8jKB+mY/t2dBxxw7t/YtQHhQLSPVlQ5aiQLaKpCYaYQ89u7HESDInKZq+UKKxOHOixY/MnLir3UN05XXaM0by+LVimNR5zQ/SDkgeffaQgX14LjDDbh8WKvjhDXskYhi/ROGXdYzgdpNN9KsMnGgQvfwWPUW0lbvaUWDGEAhpUqg3tDIrlHwgpPOZTR/XcrO31lhuY3U1EZN97HVXcgljI/iWwMQUqQAv1G28pv582F0s9OI0sU1mGET4mG7UQG3cQZcVr289ZXTFIPRP6wlajy8/nIj8yYFXlu7GA3nA="
  # AWS_ACCESS_KEY
  - secure: "n1UyDHhl7YzftHXJBk3t5bQSdekrgNezY6R73sY9Qcax/e8qcmFeJTZ//atDa6HCJAj0xta6JA9egrNok3prM9zasUU5eTXv1zNQNFS9Uj1X0sOuA6DfyU2YxxaHUeMa9U31Ib9hpeLabTLFU08raDCjo1b3qiPcPLnU0coKCYUK79heg4wrQ+hG1x1Dm7BYpGQTkht4X1yRQUPNY1vVDEM1JDZhZrCaqNISxDJCnQJkvMFXFapYh4J/VLhTkoXJ396WUw0c3d9WFqfgVqFfhgzy8lA3HlOr1VFBdflU3F7tB/9vrFR9qYJMAZqr6h0NI5xXU5vnRwHgOUJjaan3Gdamou9JyZ6rfhbWJMc2sfUQpMRuZQ9uDcwS1a8kBurYZZuq14HcWe0cKN7c65WSCyEatzdJcz5/lb2DUUXf/6/mliN6wzanzMIzMlRN4amNGOZ53+4/a/5eClnVMR966WloqHzYhEg0U9Msut4iuD1kJGtUjweZLubcfIwyUL0Cg0kvSve0AejTHLDfeqvf74a2mR7NdqdvgjhNA6TZwtiwhyQxEvqFnV9widkbqa1JF2lSJDJxxSnNEWtGAN8k4MVgKyFCyOMbTCXxW1ap7qzOJgdOsZIQgT5+6uwYSZbHK7u9mtNiZMjrYoiIi8PtZTe1lUEwdReRAGCN5+5PvJM="
  # AWS_SECRET_KEY
  - secure: "jargTrwN0uNVtRYy+zpPghJe2TA6VQYV+il2SJnFZvZp6FvDIXzvE9S5Tm6ES4oVXgQrA1uKJv4z4+Jv4i1KVMv8NF9drjnTC/eOzzItaznQmAIEYCs5JnK2+yee5Dz3x+TlohNIev+w5CEzFIWAIjbXgOt4paVVi3JuOUQ4LZ3afhE1NUUREvzfEOfJB4TLeXzLJkqAAnKWEoRzfCJtAR1890OuaVqchsktqDePVigHT5aIZnWWSArIkVz3joXZiTLCcGQqVPJlVk0ZxZhE6qS1iH0iDbJP/1ipDQguhCRbXz/X/TjscwMe6HwtSZ0TVv/nyupTZS4DgXB7TgC0gu9dqFeSiCJ+CeVaK3B88423y9OVUbMK5Tw0fElVS79c7nWa7+qV/TZypOA8H0hgTRNc2YIyvELGh3WcZLn7uNOImH2MLgV2NrUoNd8+/mgpEb7LR2WU09gchhKh30DAijP0zbO7/BezJsSPRaV+Q/lBBA0JG9hJYnkODoHaxvyJOsxzMzNB1ZviGg4omrWufUqkXnYkZ+fx7k28nuOHa7QE0784NUcSG7D1gUtsngtrr5IMrD4CeiaTMgEp3QKDfZGFTD19NDN0WttvnJRFINHJwNbkgICjpZ5/ZoiIkkDzAn/ZplwhtwfvxH8bEKLkue6q8oGA5bxf5fYCryJr5xM="
