name: TypeDoc Update

on:
  push:
    branches:
      - main

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci --unsafe-perm
      - run: npm run build
      - run: npm test
      - run: npm run build:doc
      - run: git config --global user.email "typedoc@nextapp.co"
      - run: git config --global user.name "TypeDoc"
      - run: git commit -m "TypeDoc documentation updated"
      - run: git push
